packages:
    - ./package
    - ./test

autoInstallPeers: false
strictPeerDependencies: false

catalogs:
    dev:
        "oxfmt": 0.50.0
    peer:
        "oxfmt": ^0.50.0

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/*"
    - "@rolldown/*"
    - "rolldown"
    - "@tsdown/*"
    - "tsdown"
